# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.version.version)
np.show_config()

1.13.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['F:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'F:/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['F:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'F:/Anaconda3\\Library\\inclu

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
 nulv = np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [6]:
nulv.nbytes


80

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
# add question mark after function name
python -c "import numpy; numpy.info(numpy.add)"

SyntaxError: invalid syntax (<ipython-input-5-2b389002c993>, line 2)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
nulv2 = np.zeros(10)
nulv2[4] = 1

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [20]:
rangevec = np.array(range(10,50))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [24]:
rangevec[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [25]:
matrix = np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [30]:
arr = np.array([1,2,0,0,4,0])
np.nonzero(arr)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [28]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [35]:
randarr = np.random.rand(3,3,3)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [38]:
a = np.random.rand(10,10)
amax = a.max()
amin = a.min()

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [44]:
vec = np.random.rand(30)
mean = vec.mean()

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [61]:
b = np.zeros((4,4))
b[0] = b[3] = b[:,0] = b[:,3] = 1
#better way
c = np.zeros((2,2))
c = np.pad(c,pad_width=1,mode = 'constant', constant_values = 1)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [64]:
np.pad(array = c,pad_width=1,mode = 'constant', constant_values = 0)

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

nan
False
False
np.nan
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [7]:
np.diag(range(1,5),-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [28]:
z = np.zeros((8,8))

z[0::2,0::2] = 1
z[1::2,1::2] = 1
print(z)

[[ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [31]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [34]:
arr = np.array([[0,1],[1,0]])
np.tile(arr,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [37]:
r = np.random.rand(5,5)
rmax,rmin = r.max(), r.min()
r = (r - rmin)/(rmax - rmin)

array([[ 0.25093103,  0.73985426,  0.31612283,  0.47755393,  0.        ],
       [ 0.88898166,  0.46961431,  0.99724563,  0.4997579 ,  0.58531616],
       [ 0.67163931,  0.30647532,  0.12949272,  0.93154182,  0.09743271],
       [ 0.66737274,  0.36116009,  0.73845107,  0.71936721,  0.75122548],
       [ 0.67130631,  0.58752592,  0.26411636,  1.        ,  0.75813984]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [39]:
m = np.dtype([("r",np.ubyte,1), ("g", np.ubyte,1), ("b",np.ubyte,1), ("a",np.ubyte,1)])
m

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [40]:
np.dot(np.random.rand(5,3), np.random.rand(3,2))

array([[ 1.02517037,  0.91497907],
       [ 1.4073223 ,  0.97895232],
       [ 1.32168645,  1.02564436],
       [ 1.54588509,  1.11800499],
       [ 1.45314815,  1.07587742]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [46]:
a = np.arange(10)
a[4:9] = -a[4:9]
a

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [48]:
# 9 and 10 
# but why???

SyntaxError: invalid syntax (<ipython-input-48-10e5e7cef825>, line 2)

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [57]:
# all of them except for the last one

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [65]:
# invalid value
# divide by zero
# array([ -2.14748365e+09])


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
# what is "round away"?


#### 30. How to find common values between two arrays? (★☆☆)

In [72]:
a1 = np.array(range(1,10))
a2 = np.array(range(6,16))
np.intersect1d(a1,a2)

array([6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [76]:
np.warnings.filterwarnings('ignore')

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [77]:
False

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [79]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today    = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

numpy.datetime64('2018-05-21')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [80]:
np.arange('2016-06', '2016-07', dtype='datetime64[D]')

array(['2016-06-01', '2016-06-02', '2016-06-03', '2016-06-04',
       '2016-06-05', '2016-06-06', '2016-06-07', '2016-06-08',
       '2016-06-09', '2016-06-10', '2016-06-11', '2016-06-12',
       '2016-06-13', '2016-06-14', '2016-06-15', '2016-06-16',
       '2016-06-17', '2016-06-18', '2016-06-19', '2016-06-20',
       '2016-06-21', '2016-06-22', '2016-06-23', '2016-06-24',
       '2016-06-25', '2016-06-26', '2016-06-27', '2016-06-28',
       '2016-06-29', '2016-06-30'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [92]:
a = np.arange(4)
b = np.arange(4)
np.dot(np.add(a,b),-a/2)


-14.0

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [104]:
s = np.random.rand(7)*10

np.floor(s)
np.ceil(s) - 1
s.astype(int)
s//1
s - s%1

[ 0.08742872  4.25516975  8.17000092  7.36081608  3.89758158  0.95671302
  4.59257899]


array([ 0.,  4.,  8.,  7.,  3.,  0.,  4.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [110]:
a = np.arange(5)
np.tile(a,5).reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [115]:
np.linspace(0,1,12,endpoint=True)[1:-1]

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [117]:
j = np.random.rand(10)
j.sort()



#### 41. How to sum a small array faster than np.sum? (★★☆)

In [118]:
np.add.reduce(j)

5.5845572582505865

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [124]:
a = np.random.rand(3)
b = np.random.rand(3)
np.array_equal(a,b)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [125]:
a = np.arange(10)
a.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
arr = np.random.random((10,2))
x =arr[:,0]
y =  arr[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [130]:
b[b.argmax()] = 0

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [ ]:
# ????

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [141]:
x = np.random.rand(8)
y = np.random.rand(8)
c = np.zeros((8,8))
for i in range(0,8):
    for j in range(0,8):
        c[i,j] = 1/(x[i] - y[j])


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
# ????

#### 49. How to print all the values of an array? (★★☆)

In [143]:
np.set_printoptions(threshold=np.nan)
print(np.ones((100,100)))

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1. 

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [151]:
a = np.arange(10) + np.random.rand(10)
scalar = 4
minind = np.argmin(np.abs(a - scalar))
a[minind]

3.2092516422870818

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
# ????

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
# ??????

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [152]:
a = np.arange(10, dtype=np.int32)
a = a.astype(np.float32, copy=False)

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
res  = np.genfromtxt(filename, delimiter=",")

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)